CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    username VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    balance DECIMAL(18, 2),
    currency VARCHAR(10) DEFAULT 'TRY',
    created_at TIMESTAMP
);
ALTER TABLE customers ALTER COLUMN id RESTART WITH 1000;

CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name VARCHAR(50) UNIQUE NOT NULL,
    total_size DECIMAL(18, 6) NOT NULL,
    usable_size DECIMAL(18, 6) NOT NULL,
    price DECIMAL(18, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE assets ALTER COLUMN id RESTART WITH 1000;

CREATE TABLE customer_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    total_size DECIMAL(18, 6) NOT NULL,
    usable_size DECIMAL(18, 6) NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (asset_id) REFERENCES assets(id),
    UNIQUE (customer_id, asset_id)
);
ALTER TABLE customer_assets ALTER COLUMN id RESTART WITH 1000;

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name VARCHAR(255),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    customer_id BIGINT,
    order_side VARCHAR(10),
    price DECIMAL(38, 2),
    size DECIMAL(38, 2),
    status VARCHAR(10),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    CHECK (order_side IN ('BUY', 'SELL')),
    CHECK (status IN ('CANCELED', 'MATCHED', 'PENDING'))
);
ALTER TABLE orders ALTER COLUMN id RESTART WITH 1000;

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    type VARCHAR(10),
    amount DECIMAL(18, 2),
    iban VARCHAR(34),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    CHECK (type IN ('DEPOSIT', 'WITHDRAW'))
);
ALTER TABLE transactions ALTER COLUMN id RESTART WITH 1000;