CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    username VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    balance DECIMAL(18, 2),
    created_at TIMESTAMP
);
ALTER TABLE customers ALTER COLUMN id RESTART WITH 1000;

CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    asset_name VARCHAR(50),
    total_size DECIMAL(18, 6),
    usable_size DECIMAL(18, 6),
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name VARCHAR(255),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    customer_id BIGINT,
    order_side VARCHAR(10),
    price DECIMAL(38, 2),
    size DECIMAL(38, 2),
    status VARCHAR(10),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    CHECK (order_side IN ('BUY', 'SELL')),
    CHECK (status IN ('CANCELED', 'MATCHED', 'PENDING'))
);
ALTER TABLE orders ALTER COLUMN id RESTART WITH 1000;

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    type VARCHAR(10),
    amount DECIMAL(18, 2),
    iban VARCHAR(34),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    CHECK (type IN ('DEPOSIT', 'WITHDRAW'))
);
